### ISSUE TITLE
As a food shelf client, be able to view a more organized page for making requests

### ISSUE THREAD

**Issue by Harry58326** [UMM-CSci-3601-S23/iteration-2-alex-jaydon-chenfei-harry#21]

**Comment by Harry58326** [comment]
People who want food are able to go back and edit their needs in case of any misspelling.

**Comment by Harry58326** [comment]
There will be a limit function which limits the amount of food.

**Comment by stanislowskij** [comment]
Extra note: Request forms NEED to have a NAME, and maybe put quantities. The names should not show up on the donor view, only the volunteer view

**Comment by stanislowskij** [comment]
We got this mostly resolved. The request form now has a form for the name on it. I would have liked to change "item type" to title and "food type" to description, but we can possibly save that for next iteration once we have our data more organized.
