### ISSUE TITLE
As a volunteer, be able to edit submitted requests for clarification

### ISSUE THREAD

**Issue by ChenfeiP** [UMM-CSci-3601-S23/iteration-2-alex-jaydon-chenfei-harry#23]

**Comment by stanislowskij** [comment]
We don't have time to finish this before our presentation.

**Comment by trinc005** [comment]
Ignore previous comment. I wasn't aware that Alex was already working on this feature while we were doing other things. This is now mostly done minus testing.

-- Jaydon (on Alex's account)
